export interface ListaRefeicoesTypes {
  id: number;
  nome: string;
  preco: number;
  codigo: string;
  descricao: string;
}

export const lista_refeicoes: ListaRefeicoesTypes[] = [
  {
    id: 1,
    nome: "Angus Burger",
    preco: 15,
    codigo: "04e8cfee-2d35-42e8-9554-67b2840fa283",
    descricao: "Hambúrguer feito com carne bovina de gado Angus. O nome 'Angus burger' é usado por várias cadeias de hambúrgueres de fast-food para um ou mais hambúrgueres 'premium'; no entanto, não pertence a nenhuma empresa. Hambúrgueres Angus congelados pré-fabricados estão cada vez mais disponíveis nos varejistas.",
  },
  {
    id: 2,
    nome: "Cheeseburger",
    preco: 17,
    codigo: "f749bf18-f18b-4aeb-a89c-ff7f71356a1d",
    descricao: "Hambúrguer acompanhado de queijo derretido. O próprio termo é uma junção das palavras 'queijo' e 'hambúrguer'. O queijo geralmente é fatiado e adicionado pouco tempo antes do hambúrguer terminar de cozinhar para permitir que derreta. Em restaurantes de fast food, o queijo que é adicionado ao cheeseburger é tipicamente americano, mas existem muitas outras variações. Mussarela, queijo azul, queijo suíço, pimenta jack e especialmente cheddar são escolhas populares.",
  },
  {
    id: 3,
    nome: "Rice Burger",
    preco: 18,
    codigo: "227ec513-b722-4d4c-9b08-7ae2412acda6",
    descricao: "Estilo de hambúrguer em que o pão é um bolo de arroz comprimido. A cadeia de restaurantes de fast-food MOS Burger introduziu o hambúrguer de arroz em 1987 e, desde então, tornou-se um item alimentar popular no leste da Ásia.",
  },
  {
    id: 4,
    nome: "Slug Burger",
    preco: 21,
    codigo: "623002a0-122b-4470-bdab-01bdddc9fc99",
    descricao: "Delicadeza tradicional do sul encontrada no nordeste do Mississippi, particularmente Booneville e Corinto. A receita original foi feita para ajudar as pessoas a aumentar sua oferta de carne bovina, adicionando migalhas de pão velhas à carne. O nome vem do hambúrguer originalmente custando 5 centavos, ou um níquel (uma 'lesma'). Hoje, um slugburger é um hambúrguer feito de uma mistura de carne bovina ou suína e um extensor barato, como soja ou farinha de soja, é frito em óleo. Normalmente é servido em um pão com mostarda, picles, cebola e, em alguns lugares, com batatas fritas.",
  },
  {
    id: 5,
    nome: "X-hamburguer",
    preco: 10,
    codigo: "eeef22f5-082e-458b-8749-2047a98244b6",
    descricao: "Hambúrguer é um alimento que consiste em recheios - geralmente um hambúrguer de carne moída, geralmente carne bovina - colocados dentro de um pão fatiado ou pão. Hambúrgueres são frequentemente servidos com queijo, alface, tomate, cebola, picles, bacon ou chilis; condimentos como ketchup, mostarda, maionese, relish ou um 'molho especial', muitas vezes uma variação do molho Thousand Island; e são frequentemente colocados em pães de sementes de gergelim.",
  },
  {
    id: 6,
    nome: "Barbecue Burger",
    preco: 25,
    codigo: "f8d28e71-328a-4fca-94ad-91129520ce3d",
    descricao: "Preparado com carne moída, misturado com cebola e molho barbecue, e depois grelhado. Uma vez que a carne tenha sido virada uma vez, o molho barbecue é espalhado por cima e grelhado até o molho caramelizar. O pão é untado com manteiga e também espalhado com uma leve camada de molho barbecue, depois torrado na grelha.",
  },
  {
    id: 7,
    nome: "Chili Burger",
    preco: 11,
    codigo: "55fcff6e-22ce-4130-a9fb-e9c7ff01d3d6",
    descricao: "Consiste em um hambúrguer, com a empada coberta com chili com carne.",
  },
  {
    id: 8,
    nome: "Kiwiburger",
    preco: 30,
    codigo: "57f0c932-d427-4073-8401-3cf6bc31cd0c",
    descricao: "Ingredientes populares de hambúrgueres regionais na Austrália e Nova Zelândia incluem beterraba enlatada, abacaxi e ovo frito. Na foto é um hambúrguer com fatias de beterraba enlatada dentro dele.",
  },
  {
    id: 9,
    nome: "Salmon Burger",
    preco: 32,
    codigo: "be54fadd-e987-4d4e-ad3d-ff63c118251a",
    descricao: "Fishcake feito principalmente de salmão no estilo de um hambúrguer. Hambúrgueres de salmão são especialmente comuns no Alasca, onde são oferecidos rotineiramente como uma alternativa aos hambúrgueres de carne bovina.",
  },
  {
    id: 10,
    nome: "Steak Burger",
    preco: 14,
    codigo: "1f10129a-518d-4d28-a240-0d8352eaf5b7",
    descricao: "Normalmente preparado com carne de bife moída, fatiada ou picada. Carnes adicionais também são usadas.",
  },
  {
    id: 11,
    nome: "Buffalo Burger",
    preco: 18,
    codigo: "3e485e7d-d6ae-411d-afe1-8dd1a5dd030a",
    descricao: "Preparados com carne do bisonte americano, hambúrgueres de búfalo têm menos colesterol, menos gordura e menos calorias do que hambúrgueres de carne bovina e de frango. A American Heart Association recomendou hambúrgueres de búfalo em 1997 como mais saudáveis para o coração do que frango ou carne bovina.",
  },
  {
    id: 12,
    nome: "Chori Burger",
    preco: 27,
    codigo: "e62484de-2bf3-4d68-a3f1-d1fb5bf0dc04",
    descricao: "um hambúrguer filipino feito caracteristicamente com rissóis de chouriço (longganisa), ketchup de banana, maionese e atchara, além de tomate e alface. Foi popularizado pela primeira vez pelo Merly's BBQ, uma barraca de comida de rua na ilha de Boracay, nas Filipinas.",
  },
  {
    id: 13,
    nome: "Luther Burger",
    preco: 21,
    codigo: "a48a70f5-5104-4252-aaad-f4449ced2a24",
    descricao: "Hambúrguer ou cheeseburger preparado com uma ou mais rosquinhas vitrificadas no lugar do pão",
  },
  {
    id: 14,
    nome: "Slaters 50/50 burger",
    preco: 8,
    codigo: "4c73eb61-a60b-40b8-aae0-d94e354954ab",
    descricao: "Meio bacon moído, meio hambúrguer de carne moída desenvolvido por Scott Slater para o restaurante Slater's 50/50. Outra variedade é metade de carne de canguru e metade de bacon.",
  },
  {
    id: 15,
    nome: "Steamed Cheeseburger",
    preco: 9,
    codigo: "e1ab70dd-c745-4cdd-9088-bc0b142eb083",
    descricao: "Em vez de ser frito em uma panela ou grelhado em uma grelha, um cheeseburger no vapor é cozido no vapor em um armário de aço inoxidável contendo bandejas que contêm um hambúrguer ou um pedaço de queijo. Este método de cozimento faz com que a gordura da carne derreta, resultando em um hambúrguer úmido e suculento que é então colocado em um pão e coberto com o queijo derretido. Várias coberturas habituais podem então ser adicionadas ao hambúrguer.",
  },
  {
    id: 16,
    nome: "Butter Burger",
    preco: 15,
    codigo: "5b0c56f2-c231-43e4-b96a-102898b24969",
    descricao: "No Upper Midwest, particularmente Wisconsin, os hambúrgueres são muitas vezes feitos com um pão amanteigado, manteiga como um dos ingredientes do hambúrguer ou com um pedaço de manteiga em cima do hambúrguer.",
  },
  {
    id: 17,
    nome: "Hawaii Burger",
    preco: 27,
    codigo: "7b2952b1-4ad7-4cb8-ae4a-f2fd4093e112",
    descricao: "Coberto com abacaxi e muitas vezes molho teriyaki (da cultura nipo-americana)",
  },
  {
    id: 18,
    nome: "Oklahoma Onion Burger",
    preco: 23,
    codigo: "37f4f852-96b0-4eca-af81-e6e361c00d12",
    descricao: "Um hambúrguer que tem muitas cebolas amarelas em fatias finas empilhadas em cima da carne moída antes de esmagar. Foi concebido durante a Grande Depressão no oeste de Oklahoma como uma maneira de os clientes locais estenderem o suprimento de carne bovina de um restaurante.",
  },
  {
    id: 19,
    nome: "Slider Burger",
    preco: 25,
    codigo: "47bb1a62-3c1f-4f14-8d62-5717d172675f",
    descricao: "Refere-se principalmente a pequenos hambúrgueres, mas também pode cobrir qualquer pequeno sanduíche servido em um rolo deslizante",
  },
  {
    id: 20,
    nome: "Teriyaki Burger",
    preco: 13,
    codigo: "c3600a83-06fb-4755-868b-243c0a313f28",
    descricao: "Hambúrguer teriyaki refere-se a uma variedade de hambúrguer coberto com molho teriyaki ou com o molho trabalhado no hambúrguer de carne moída.",
  },
  {
    id: 21,
    nome: "California Burger",
    preco: 20,
    codigo: "feac6d6c-01fa-463b-9d78-32cf2c80704b",
    descricao: "No oeste dos EUA, um hambúrguer 'Califórnia' geralmente consiste em um cheeseburger normal, com a adição de bacon e guacamole ou abacate. No leste dos EUA, o California Burger é tradicionalmente um hambúrguer com alface, tomate e cebola crua.",
  },
  {
    id: 22,
    nome: "Jucy Lucy cheeseburger",
    preco: 13,
    codigo: "fddad7c5-a7f4-46da-bdd1-80c943b8f9df",
    descricao: "Um cheeseburger que tem o queijo dentro do hambúrguer de carne e não no topo. Um pedaço de queijo é cercado por carne crua e cozido até derreter, resultando em um núcleo de queijo fundido dentro do hambúrguer.",
  },
  {
    id: 23,
    nome: "Patty Melt burger",
    preco: 18,
    codigo: "9d9715b9-a562-4691-90ab-8dc1c57d73de",
    descricao: "Sanduíche de hambúrguer composto por um hambúrguer de carne moída, pedaços de cebola salteada ou grelhada e Cheddar ou queijo suíço entre duas fatias de pão (tradicionalmente centeio, embora às vezes seja substituído).",
  },
  {
    id: 24,
    nome: "Slopper burger",
    preco: 27,
    codigo: "e1ca6619-c9af-43cf-89dc-0be705ad4f1f",
    descricao: "Cheeseburger, ou hambúrguer servido aberto e envolto em chile vermelho ou chile verde (também conhecido como chile verde ou molho de chile verde). Sloppers geralmente incluem pães grelhados e muitas vezes são cobertos com cebolas frescas picadas. Comer um slopper não é tarefa fácil. O uso de garfo ou colher é essencial, mas recomenda-se a combinação de garfo e faca ou garfo e colher.",
  },
  {
    id: 25,
    nome: "Veggie burger",
    preco: 33,
    codigo: "3df04416-9223-49e7-8c8c-41b7b4c2c33c",
    descricao: "Hambúrguer vegetariano, hambúrguer de jardim ou hambúrguer de tofu usa um análogo de carne, um substituto de carne como tofu, proteína vegetal texturizada, seitan (glúten de trigo), Quorn, feijão, grãos ou uma variedade de vegetais, que são moídos e moldados em hambúrgueres.",
  },
  {
    id: 26,
    nome: "Kimchi burger",
    preco: 31,
    codigo: "3988dfa6-922f-4f64-bc75-1dfc3c581c2c",
    descricao: "Um hambúrguer que inclui kimchi em sua preparação",
  },
  {
    id: 27,
    nome: "Coca-cola 1,5l",
    preco: 4.5,
    codigo: "55d648e3-1c93-4f31-950b-dd5d88e3d95f",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 28,
    nome: "Coca-cola 1l",
    preco: 4,
    codigo: "500acc0d-a444-43ef-b1b2-3965c40e5596",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 29,
    nome: "Coca-cola 2,5l",
    preco: 6,
    codigo: "76a6eb62-2744-4bc9-ad12-3b25b3300265",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 30,
    nome: "Coca-cola 200ml",
    preco: 2,
    codigo: "626f2c5f-2b8f-4b01-ae2c-589c267e7fc5",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 31,
    nome: "Coca-cola 220ml",
    preco: 2.5,
    codigo: "3dd3761a-d888-4905-825e-0b31aac0cafe",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 32,
    nome: "Coca-cola 2l",
    preco: 5,
    codigo: "392eed80-3b5e-4373-91d9-d66fed93bb6b",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 33,
    nome: "Coca-cola 350ml",
    preco: 3,
    codigo: "96ce12cd-b430-47e8-b4f4-ca11900bf9fe",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 34,
    nome: "Coca-cola 3l",
    preco: 7,
    codigo: "635a2f6d-3ff3-4b31-af91-eff6f76f35f7",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 35,
    nome: "Coca-cola 600ml",
    preco: 3.5,
    codigo: "7ef10fab-b97b-44c8-83c7-d02458053748",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
  {
    id: 36,
    nome: "Coca-cola 600ml",
    preco: 3.5,
    codigo: "c5ed0d01-3b4f-4398-9cfe-e0b27263c1af",
    descricao: "Coca-Cola é um refrigerante carbonatado fabricado pela Coca-Cola Company.",
  },
];